---
- name: check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Check if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed

- name: kill all k3s resources
  shell: /usr/local/bin/k3s-killall.sh
  when: k3s_installed.stat.exists == true

- name: uninstall k3s
  shell: /usr/local/bin/k3s-agent-uninstall.sh
  when: k3s_installed.stat.exists == true

- name: Remove docker resources
  ignore_errors: yes
  shell: docker stop $(docker ps -a -q --filter "name=k8s_") | xargs docker rm
  when: docker_installed.stat.exists == true
