---
- hosts: kube_master[0]
  any_errors_fatal: true
  roles:
    - logging
    - nfs-server
    - nfs-provisioner
    - metallb
    - traefik
    - kube-dashboard
    - cloudflare-ddns
    - gitea
    - openvpn
    - external-services
