---
- name: Check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Check if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_installed

- name: Kill all k3s resources
  shell: /usr/local/bin/k3s-killall.sh
  when: k3s_installed.stat.exists == true

- name: Uninstall k3s
  shell: /usr/local/bin/k3s-uninstall.sh
  when: k3s_installed.stat.exists == true

- name: Remove docker resources
  ignore_errors: yes
  shell: docker stop $(docker ps -a -q --filter "name=k8s_") | xargs docker rm
  when: docker_installed.stat.exists == true

- name: Remove temp files directory
  become: yes
  file:
    path: "{{ temp_dir }}"
    state: absent

- name: Create temp directory
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Remove nfs exports
  become: yes
  file:
    path: /etc/exports
    state: absent

- name: Remove nfs-kernel-server package
  become: yes
  apt:
    name: nfs-kernel-server
    state: absent

- name: Reset mount
  become: yes
  mount:
    path: "{{ storage.location }}"
    src: "{{ storage.device }}"
    fstype: ext4
    state: absent
  when: storage.storage_type == "device"

- name: Create a ext4 filesystem on storage device
  become: yes
  filesystem:
    fstype: ext4
    force: true
    dev: "{{ storage.device }}"
  when: storage.storage_type == "device" and storage.wipe == true

- name: Remove storage files directory
  become: yes
  file:
    path: "{{ storage.location }}"
    state: absent
  when: storage.storage_type == "local" and storage.wipe == true
